### PR TITLE
Added a input type to hide what is typed and a helper method to calcu…

### PR DESCRIPTION
**Pull request by ulucs**
late the number of UTF-8 characters in a string

### CODE REVIEW

**Comment by pgimeno** [comment]
Thank you. While I like the idea of having a password entry control, I think it should be integrated as part of the normal input control, rather than duplicating the input control's code. Also, the substitution character should be configurable instead of fixed.

Do you think you can rework the code to integrate password entry in the normal input control? It should be as simple as having a property like `pwchar` or similar, which does the substitution in the output when set.

**Comment by ulucs** [comment]
here goes

**Comment by pgimeno** [comment]
Thank you, much better! One last thing. I'm just wondering if it's worth having `ispassword` at all. I understand that you want to provide a default value, but maybe we can do it this way instead:

- Get rid of `ispassword`.
- Don't pass `passwordchar` or set it to `nil` or `false` to use the control as a normal edit control.
- Pass `passwordchar = true` to use the default `'*'`.
- Pass `passwordchar = 'char'` to use a custom value.

I think that'd work best. What do you think? Is there any good reason to keep `ispassword`?

**Comment by ulucs** [comment]
`passwordchar` defining both behavior and cosmetics violates single responsibility, therefore making the process harder to read and more prone to bugs for any other person editing it. Also I'd rather not make programmers coming from other languages hesitate due to empty string shenanigans (JS evaluates `""` as `false`, so a JS programmer may be confused if he tries to make a unix-style password entry)

**Comment by pgimeno** [comment]
OK, you've convinced me. Thanks for the contribution!

**Pull request merged**
